### ISSUE TITLE
Script for updating firmware of all the boards not working properly

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-firmware-build#158] opened 2024-07-24 10:02 UTC
Today I used the script `FirmwareUpdater.script.update.all.sh` on `ergoCubSN001` to update the firmware of all the boards. Only the `EMS` and `FOC` boards have been updated, while the script did not update the firmware of the `MC4PLUS` and `AMC` boards. In addition the firmware of 2 EMS boards was not uploaded correctly, indeed when restarted the boards they were not able to go in application mode and I had to re-flash the firmware manually.

I did not notice any error on the terminal.

**Comment by valegagge** [comment] 2024-07-26 10:44
Hi @isorrentino, 
thanks for the report. Have you the output of the script?

**Comment by isorrentino** [comment] 2024-07-26 11:00
> thanks for the report. Have you the output of the script?


No sorry, I haven't saved it.

**Comment by valegagge** [comment] 2024-07-26 11:12
So, to understand what is happening I need to re-perform the update.
@davidetome checked the scripts successfully.

**Comment by valegagge** [comment] 2024-09-02 07:39
Maybe the failure is due to this issue: https://github.com/robotology/icub-firmware/issues/507.

We still need to verify.

**Comment by marcoaccame** [comment] 2024-09-02 07:46
> Maybe the failure is due to this issue: [robotology/icub-firmware#507](https://github.com/robotology/icub-firmware/issues/507).
> 
> We still need to verify.

the issue is related only to `mtb4c`.

**Comment by valegagge** [comment] 2024-09-02 09:32
> > Maybe the failure is due to this issue: [robotology/icub-firmware#507](https://github.com/robotology/icub-firmware/issues/507).
> > We still need to verify.
> 
> the cited issue is related only to `mtb4c`.

yes, I know, but maybe that failure on mtb4c makes the whole process fail. This is a supposition. we need to verify

**Comment by valegagge** [comment] 2024-09-05 11:47
ok! thanks @marcoaccame

**Comment by valegagge** [comment] 2024-09-23 10:19
> Action points:
> 1. open an issue to report the bug related to the AMC board.

https://github.com/icub-tech-iit/sw-management/issues/172

> 2. open a pr to update all the scripts.
https://github.com/robotology/icub-firmware-build/pull/163

**Comment by valegagge** [comment] 2024-09-27 10:23
Closing. Please @isorrentino if you see any another problem open a new issue and add the log.

Thanks heap!

**Comment by isorrentino** [comment] 2024-09-27 10:24
Sure, thank you all!

**Closed by valegagge** 2024-09-27 10:23 UTC
Labels: bug
